services:
  - type: web
    name: washwish-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn detergee.wsgi
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: washwish.web.app,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: washwish-db
          property: connectionString 