# Generated by Django 3.1.7 on 2025-09-27 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0019_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordernumber',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicetype'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='statusid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.orders'),
        ),
    ]
