# Generated by Django 3.1.7 on 2025-10-22 15:00

from django.db import migrations

def populate_data(apps, schema_editor):
    ClothType = apps.get_model('services', 'ClothType')
    ServiceType = apps.get_model('services', 'ServiceType')
    Status = apps.get_model('services', 'Status')
    
    # Create cloth types
    cloth_types = ['Shirts', 'Pants', 'Dresses', 'Jackets', 'Bedsheets', 'Towels']
    for cloth in cloth_types:
        ClothType.objects.get_or_create(clothtypes=cloth)
    
    # Create service types
    services = [
        ('Dry Cleaning', 50),
        ('Washing', 30),
        ('Ironing', 20),
        ('Folding', 15),
    ]
    for service, price in services:
        ServiceType.objects.get_or_create(
            servicetypes=service, 
            defaults={'price': price}
        )
    
    # Create status types
    statuses = ['Received', 'In Progress', 'Washing', 'Drying', 'Ironing', 'Completed']
    for status in statuses:
        Status.objects.get_or_create(status=status)

def reverse_populate_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20250927_2000'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_populate_data),
    ]
